on:
  push:
    branches:
    - main
    - release/*
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: src/
        remote_path: /var/www/html/
        remote_host: 165.227.142.203
        remote_user: debian
        remote_key: ${{ secrets.DEPLOY_KEY_PRIVATE }}
